name: Build master

on:
  push:
    branches:
      - "master"

env:
  OPAMROOT: /home/opam/.opam

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:ubuntu-20.04-ocaml-4.14
      options: --user root

    steps:
      - run: opam --version
      - run: opam exec -- ocamlopt --version
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      # checking out the code seems to be important because local switch is used
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # docker has opam 2.0.x where depext is not yet integrated
      - run: opam depext yojson cohttp lwt websocket-lwt-unix lwt_ppx js_of_ocaml-ppx ppx_inline_test --yes
      - run: opam install yojson cohttp lwt websocket-lwt-unix lwt_ppx js_of_ocaml-ppx ppx_inline_test --yes
      - run: opam exec -- dune build @default --profile=release
